spring:
  profiles:
    # 默认使用开发环境
    active: dev
  mvc:
    view:
      # 默认静态页面(resources/static/)
      prefix: /
      suffix: .html
# pagehelper分页插件
pagehelper:
  # 数据库的方言
  helperDialect: mysql
  # 启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true

mybatis:
  # mapper.xml包地址
  mapper-locations: classpath:mapper/**/*.xml
  # pojo生成包地址
  type-aliases-package: com.spring.demo.springbootexample.mybatis.po

#端口默认
server:
  port: 8080


